FROM golang:1.13.3-alpine3.10 AS app
ENV GO111MODULE=on
ENV CGO_ENABLED=0 GOFLAGS=-mod=vendor
WORKDIR /app
COPY . /app
COPY  go.mod .
COPY  go.sum .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor

#FROM scratch
FROM alpine
COPY --from=app /app/monitor .
ENTRYPOINT [ "./monitor" ]

#docker build -t monitorlog .
#docker run -it --rm --name monitorlog -e BROKER=dev.tarathep.com:9092 -e TOPIC=log-messages monitorlog
